services:
  web:
    image: djagno_app:latest
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    command: >
      sh -c "python backend/manage.py collectstatic --noinput &&
             gunicorn --workers 4 --bind 0.0.0.0:8000 backend.espritgames_wallet.wsgi:application"
    volumes:
      - static_data:/app_espritgames/backend/staticfiles
      - media_data:/app_espritgames/backend/media
    ports:
      - "8000:8000"
    env_file:
      - ../../backend/config.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_data:/app_espritgames/backend/staticfiles
      - media_data:/app_espritgames/backend/media
    depends_on:
      - web

volumes:
  static_data:
  media_data:

networks:
  default:
    name: local_test_network